name: Pyright Type Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'  # Specify the Node.js version compatible with Pyright

    - name: Install Pyright
      run: |
        npm install -g pyright  # Install Pyright globally using npm

    - name: Save Pyright Output
      run: pyright > pyright_output.txt

    - name: Upload Pyright Output
      uses: actions/upload-artifact@v2
      with:
        name: pyright-report
        path: pyright_output.txt

